to_italian = {
    'garam masala': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'elbow macaroni': ['spaghetti', 'gnocchi'],
    'monterey jack cheese': ['ricotta cheese', 'mozzarella cheese'],
    'ketchup': ['marinara sauce'],
    'saffron': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'cabbage': ['kale', 'yellow squash', 'zucchini', 'spinach'],
    'bacon': ['pancetta'],
    'green chillies': ['red bell pepper'],
    'kielbasa': ['italian sausage'],
    'bay leaves': ["parsley", "oregano"],
    'margarine': ['olive oil'],
    'cauliflower': ['yellow squash', 'zucchini'],
    'teriyaki sauce': ['balsamic vinaigrette'],
    'mirin': ['balsamic vinaigrette'],
    'sesame oil': ["olive oil"],
    'pinto beans': ['kidney beans'],
    'rice vinegar': ["balsamic vinegar"],
    'fresh chives': ['red onion'],
    'chives': ['red onion'],
    'broccoli': ['yellow squash', 'zucchini'],
    'american cheese': ['mozzarella cheese'],
    'chili beans': ['kidney beans'],
    'sesame seeds': ["fennel seed"],
    'barbeque sauce': ['marinara sauce', 'italian-style salad dressing', 'balsamic glaze'],
    'processed cheese': ['ricotta cheese', 'mozzarella cheese'],
    'cumin': ['italian seasoning', 'oregano', 'crushed red pepper'],
    'cumin seeds': ['fennel seeds'],
    'worcestershire sauce': ['italian-style salad dressing'],
    'gochujang': ['pumpkin puree'],
    'shortening': ['olive oil', 'butter'],
    'poppy seeds': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'enchilada sauce': ['marinara sauce', 'italian-style salad dressing'],
    'swiss cheese': ['mozzarella cheese'],
    'sake': ['red wine'],
    'refried beans': ['kidney beans'],
    'cardamom': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'cottage cheese': ['ricotta cheese'],
    'ginger': ['kale', 'yellow squash', 'zucchini', 'spinach'],
    'dashi': ['polenta'],
    'curry powder': ["crushed red pepper", "black pepper", "garlic powder"],
    'cayenne pepper': ["crushed red pepper", "black pepper", "garlic powder"],
    'chili sauce': ['marinara sauce', 'italian-style salad dressing'],
    'taco seasoning': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'black beans': ['kidney beans'],
    'green beans': ['zucchini'],
    'star anise': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'bean sprouts': ['kale', 'yellow squash', 'zucchini', 'spinach'],
    'cilantro': ['sage', 'basil'],
    'coriander': ['sage', 'basil'],
    'feta cheese': ['ricotta cheese', 'mozzarella cheese', 'parmesan cheese', 'romano cheese'],
    'hoisin sauce': ['balsamic glaze'],
    'chili powder': ["crushed red pepper", "black pepper", "garlic powder"],
    'seafood seasoning': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'sherry': ['marsala'],
    'salsa': ['marinara sauce'],
    'soy sauce': ["extra virgin olive oil"],
    'cajun seasoning': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'paprika': ["crushed red pepper", "black pepper", "garlic powder"],
    'turmeric': ["italian seasoning", "oregano", "basil", "parsley", "black pepper"],
    'cheddar cheese': ['ricotta cheese', 'mozzarella cheese'],
    'beer': ['red wine'],
    'turkey': ['italian sausage'],
    'ranch dressing': ['balsamic vinaigrette'],
    'poultry seasoning': ['italian seasoning', 'oregano', 'parsley'],
    'mushrooms': ['porcini mushrooms'],
    'hot sauce': ['Naples Drizzle'],
    'cucumber': ['yellow squash', 'zucchini'],
    'jalapeño': ["red pepper"]
}

to_mexican = {
     'garam masala': ['taco seasoning', 'cumin', 'chili powder'],
     'ketchup': ['enchilada sauce'],
     'beef': ['flank steak'],
     'mozzarella cheese': ['monterey jack cheese', 'cheddar cheese'],
     'rice': ['corn kernel', 'quinoa'],
     'saffron': ['cumin'],
     'scallops': ['shrimp'],
     'thyme': ['fresh cilantro', 'salsa', 'fresh mint'],
     'bacon': ['flank steak'],
     'fresh mint': ['fresh cilantro', 'salsa', 'fresh mint'],
     'green chiles': ['chili beans', 'black beans'],
     'sage': ['fresh cilantro', 'salsa', 'fresh mint'],
     'veal': ['flank steak'],
     'italian-style salad dressing': ['enchilada sauce'],
     'green chilies': ['chili beans'],
     'round steak': ['flank steak'],
     'yellow squash': ['chili beans', 'black beans'],
     'leeks': ['fresh cilantro', 'salsa', 'fresh mint'],
     'peas': ['corn kernel'],
     'parsley': ['fresh cilantro', 'salsa', 'fresh mint'],
     'butter': ['olive oil'],
     'white bread': ['tortillas'],
     'cannellini beans': ['chili beans', 'black beans'],
     'pear': ['avocado'],
     'miso paste': ['taco seasoning', 'cumin', 'chili powder'],
     'oil': ['olive oil'],
     'kielbasa': ['flank steak'],
     'bay leaves': ['fresh cilantro', 'salsa', 'fresh mint'],
     'italian seasoning': ['taco seasoning', 'cumin', 'chili powder'],
     'margarine': ['olive oil'],
     'dried cranberries': ['avocado'],
     'capers': ['black olives'],
     'oyster sauce': ['enchilada sauce'],
     'teriyaki sauce': ['enchilada sauce'],
     'carrot': ['black olives'],
     'cinnamon': ['cumin'],
     'pinto beans': ['refried beans', 'black beans'],
     'fresh chives': ['fresh cilantro', 'salsa', 'fresh mint'],
     'pork': ['flank steak'],
     'american cheese': ['monterey jack cheese','cheddar cheese'],
     'fish sauce': ['enchilada sauce'],
     'rolled oats': ['quinoa'],
     'ham': ['flank steak'],
     'sesame seeds': ['taco seasoning', 'chili powder', 'cumin'],
     'barbecue sauce': ['enchilada sauce'],
     'onion': ['green onion'],
     'onions': ['green onions'],
     'processed cheese food': ['monterey jack cheese'],
     'tofu': ['refried beans', 'black beans'],
     'tuna': ['shrimp'],
     'provolone cheese': ['monterey jack cheese', 'cheddar cheese'],
     'worcestershire sauce': ['enchilada sauce'],
     'oregano': ['fresh cilantro', 'salsa', 'fresh mint'],
     'apple': ['avocado'],
     'dill': ['fresh cilantro', 'salsa', 'fresh mint'],
     'poppy seeds': ['taco seasoning', 'chili powder', 'cumin'],
     'marinara sauce': ['enchilada sauce'],
     'ricotta cheese': ['monterey jack cheese', 'cheddar cheese'],
     'swiss cheese': ['monterey jack cheese', 'cheddar cheese'],
     'dried rosemary': ['taco seasoning', 'chili powder', 'cumin'],
     'cardamom': ['taco seasoning', 'chili powder', 'cumin'],
     'cottage cheese': ['monterey jack cheese', 'cheddar cheese'],
     'ginger': ['jalapeño pepper'],
     'zucchini': ['kernel corn'],
     'curry powder': ['chili powder'],
     'fennel seed': ['taco seasoning', 'chili powder', 'cumin'],
     'coconut': ['avocado'],
     'mango': ['avocado'],
     'artichoke': ['black olives'],
     'lamb': ['flank steak'],
     'green beans': ['chili beans', 'black olives', 'kernel corn'],
     'star anise': ['taco seasoning', 'chili powder', 'cumin'],
     'bean sprouts': ['chili beans', 'black olives', 'kernel corn'],
     'mustard': ['enchilada sauce'],
     'vanilla extract': ['agave'],
     'feta cheese': ['monterey jack cheese','cheddar cheese'],
     'pancetta': ['flank steak'],
     'hoisin sauce': ['enchilada sauce'],
     'basil': ['fresh cilantro', 'salsa', 'fresh mint'],
     'romano cheese': ['monterey jack cheese', 'cheddar cheese'],
     'seafood seasoning': ['taco seasoning', 'chili powder', 'cumin'],
     'shallot': ['green onion'],
     'sherry': ['avocado'],
     'caraway seed': ['taco seasoning', 'chili powder', 'cumin'],
     'pasta sauce': ['enchilada sauce'],
     'soy sauce': ['enchilada sauce'],
     'banana': ['avocado'],
     'pepper': ['jalapeño pepper'],
     'paprika': ['taco seasoning', 'chili powder', 'cumin'],
     'bay leaf': ['fresh cilantro', 'salsa', 'fresh mint'],
     'turmeric': ['taco seasoning', 'chili powder', 'cumin'],
     'cheddar cheese': ['monterey jack cheese', 'cheddar cheese'],
     'nutmeg': ['taco seasoning', 'chili powder', 'cumin'],
     'barbecue sauce': ['enchilada sauce'],
     'turkey': ['flank steak', 'chicken'],
     'parmesan cheese': ['monterey jack cheese', 'cheddar cheese'],
     'ranch dressing': ['enchilada sauce'],
     'poultry seasoning': ['taco seasoning', 'chili powder', 'cumin'],
     'mushrooms': ['chili beans', 'black olives', 'kernel corn'],
     'strawberries': ['avocado'],
     'orange': ['lime'],
     'salmon': ['shrimp'],
     'hot sauce': ['jalapeño pepper']
}